app:
    resource: @AppBundle/Controller/
    type:     annotation

post:
    resource: "@AppBundle/Controller/AuthController.php"
    type:     annotation

get:
    resource: "@AppBundle/Controller/SiteController.php"
    type:     annotation
