services:
    resource: "@ServicesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

post:
    resource: "@AppBundle/Controller/AuthController.php"
    type:     annotation
